I imported libraries and pulled data.

In [55]:
import pandas as pd
import networkx as nx
import gravis as gv
import numpy as np

In [56]:
airport_data = pd.read_csv(r"C:\Users\askin\OneDrive\Masaüstü\airports.dat.txt")
route_data = pd.read_csv(r"C:\Users\askin\OneDrive\Masaüstü\routes.dat.txt")

In [62]:
airport_data

,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081689834590001,145.391998291,5282,10,U,Pacific/Port_Moresby,airport,OurAirports
0,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10,U,Pacific/Port_Moresby,airport,OurAirports
1,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10,U,Pacific/Port_Moresby,airport,OurAirports
2,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10,U,Pacific/Port_Moresby,airport,OurAirports
3,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10,U,Pacific/Port_Moresby,airport,OurAirports
4,6,Wewak International Airport,Wewak,Papua New Guinea,WWK,AYWK,-3.583830,143.669006,19,10,U,Pacific/Port_Moresby,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7692,14106,Rogachyovo Air Base,Belaya,Russia,\N,ULDA,71.616699,52.478298,272,\N,\N,\N,airport,OurAirports
7693,14107,Ulan-Ude East Airport,Ulan Ude,Russia,\N,XIUW,51.849998,107.737999,1670,\N,\N,\N,airport,OurAirports
7694,14108,Krechevitsy Air Base,Novgorod,Russia,\N,ULLK,58.625000,31.385000,85,\N,\N,\N,airport,OurAirports
7695,14109,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,-27.261200,-70.779198,670,\N,\N,\N,airport,OurAirports
7696,14110,Melitopol Air Base,Melitopol,Ukraine,\N,UKDM,46.880001,35.305000,0,\N,\N,\N,airport,OurAirports

In [63]:
route_data

       2B    410  AER  2965  KZN  2990 Unnamed: 6  0  CR2
0      2B    410  ASF  2966  KZN  2990        NaN  0  CR2
1      2B    410  ASF  2966  MRV  2962        NaN  0  CR2
2      2B    410  CEK  2968  KZN  2990        NaN  0  CR2
3      2B    410  CEK  2968  OVB  4078        NaN  0  CR2
4      2B    410  DME  4029  KZN  2990        NaN  0  CR2
...    ..    ...  ...   ...  ...   ...        ... ..  ...
67657  ZL   4178  WYA  6334  ADL  3341        NaN  0  SF3
67658  ZM  19016  DME  4029  FRU  2912        NaN  0  734
67659  ZM  19016  FRU  2912  DME  4029        NaN  0  734
67660  ZM  19016  FRU  2912  OSS  2913        NaN  0  734
67661  ZM  19016  OSS  2913  FRU  2912        NaN  0  734

[67662 rows x 9 columns]

Then I wrote a function to clean the data.

In [64]:
def data_cleaner(dataframe, new_column_names):

    first_row = dataframe.columns.tolist()
    new_data = [first_row] + dataframe.values.tolist()
    dataframe = pd.DataFrame(new_data, columns=first_row)
    dataframe.rename(columns=new_column_names, inplace=True)

    return dataframe

In [65]:
new_airport = {'1':'Airport ID', 'Goroka Airport' : 'Airport Name', 'Goroka':'City', 'Papua New Guinea':'Country', 'GKA':'IATA', 'AYGA':'ICAO', '-6.081689834590001': 'Latitude', '145.391998291':'Longitude', '5282':'Altitude', '10':'Timezone', 'U':'DST', 'Pacific/Port_Moresby':'TZ Timezone', 'airport':'Type', 'OurAirports':'Source'}

airport_data_new = data_cleaner(airport_data, new_airport)

airport_data_new

,Airport ID,Airport Name,City,Country,IATA,ICAO,Latitude,Longitude,Altitude,Timezone,DST,TZ Timezone,Type,Source
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081689834590001,145.391998291,5282,10,U,Pacific/Port_Moresby,airport,OurAirports
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.20708,145.789001,20,10,U,Pacific/Port_Moresby,airport,OurAirports
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.82679,144.296005,5388,10,U,Pacific/Port_Moresby,airport,OurAirports
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10,U,Pacific/Port_Moresby,airport,OurAirports
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.44338,147.220001,146,10,U,Pacific/Port_Moresby,airport,OurAirports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7693,14106,Rogachyovo Air Base,Belaya,Russia,\N,ULDA,71.616699,52.478298,272,\N,\N,\N,airport,OurAirports
7694,14107,Ulan-Ude East Airport,Ulan Ude,Russia,\N,XIUW,51.849998,107.737999,1670,\N,\N,\N,airport,OurAirports
7695,14108,Krechevitsy Air Base,Novgorod,Russia,\N,ULLK,58.625,31.385,85,\N,\N,\N,airport,OurAirports
7696,14109,Desierto de Atacama Airport,Copiapo,Chile,CPO,SCAT,-27.2612,-70.779198,670,\N,\N,\N,airport,OurAirports
7697,14110,Melitopol Air Base,Melitopol,Ukraine,\N,UKDM,46.880001,35.305,0,\N,\N,\N,airport,OurAirports

In [66]:
new_route = {'2B':'Airline', '410' : 'Airline ID', 'AER':'Source Airport', '2965':'Source Airport ID', 'KZN':'Destination Airport', '2990':'Destination Airport ID', 'Unnamed: 6': 'Codeshare', '0':'Stops', 'CR2':'Equipments'}

route_data_new = data_cleaner(route_data, new_route)

route_data_new

,Airline,Airline ID,Source Airport,Source Airport ID,Destination Airport,Destination Airport ID,Codeshare,Stops,Equipments
0,2B,410,AER,2965,KZN,2990,Unnamed: 6,0,CR2
1,2B,410,ASF,2966,KZN,2990,NaN,0,CR2
2,2B,410,ASF,2966,MRV,2962,NaN,0,CR2
3,2B,410,CEK,2968,KZN,2990,NaN,0,CR2
4,2B,410,CEK,2968,OVB,4078,NaN,0,CR2
...,...,...,...,...,...,...,...,...,...
67658,ZL,4178,WYA,6334,ADL,3341,NaN,0,SF3
67659,ZM,19016,DME,4029,FRU,2912,NaN,0,734
67660,ZM,19016,FRU,2912,DME,4029,NaN,0,734
67661,ZM,19016,FRU,2912,OSS,2913,NaN,0,734
67662,ZM,19016,OSS,2913,FRU,2912,NaN,0,734

Then I merged the airport and route data twice to have both destination and source cities-airports match.

In [67]:
airport_data = airport_data_new.drop(columns = ['ICAO', 'Latitude', 'Longitude', 'Altitude', 'Timezone', 'DST', 'TZ Timezone', 'Type', 'Source'])
route_data = route_data_new.drop(columns = ['Codeshare', 'Equipments'])

merged_data = pd.merge(route_data, airport_data, left_on = "Source Airport", right_on = "IATA", how = "left")
merged_data

,Airline,Airline ID,Source Airport,Source Airport ID,Destination Airport,Destination Airport ID,Stops,Airport ID,Airport Name,City,Country,IATA
0,2B,410,AER,2965,KZN,2990,0,2965,Sochi International Airport,Sochi,Russia,AER
1,2B,410,ASF,2966,KZN,2990,0,2966,Astrakhan Airport,Astrakhan,Russia,ASF
2,2B,410,ASF,2966,MRV,2962,0,2966,Astrakhan Airport,Astrakhan,Russia,ASF
3,2B,410,CEK,2968,KZN,2990,0,2968,Chelyabinsk Balandino Airport,Chelyabinsk,Russia,CEK
4,2B,410,CEK,2968,OVB,4078,0,2968,Chelyabinsk Balandino Airport,Chelyabinsk,Russia,CEK
...,...,...,...,...,...,...,...,...,...,...,...,...
67658,ZL,4178,WYA,6334,ADL,3341,0,6334,Whyalla Airport,Whyalla,Australia,WYA
67659,ZM,19016,DME,4029,FRU,2912,0,4029,Domodedovo International Airport,Moscow,Russia,DME
67660,ZM,19016,FRU,2912,DME,4029,0,2912,Manas International Airport,Bishkek,Kyrgyzstan,FRU
67661,ZM,19016,FRU,2912,OSS,2913,0,2912,Manas International Airport,Bishkek,Kyrgyzstan,FRU
67662,ZM,19016,OSS,2913,FRU,2912,0,2913,Osh Airport,Osh,Kyrgyzstan,OSS

In [68]:
merged_data = pd.merge(merged_data, airport_data, left_on = "Destination Airport", right_on = "IATA", how = "left")
merged_data

,Airline,Airline ID,Source Airport,Source Airport ID,Destination Airport,Destination Airport ID,Stops,Airport ID_x,Airport Name_x,City_x,Country_x,IATA_x,Airport ID_y,Airport Name_y,City_y,Country_y,IATA_y
0,2B,410,AER,2965,KZN,2990,0,2965,Sochi International Airport,Sochi,Russia,AER,2990,Kazan International Airport,Kazan,Russia,KZN
1,2B,410,ASF,2966,KZN,2990,0,2966,Astrakhan Airport,Astrakhan,Russia,ASF,2990,Kazan International Airport,Kazan,Russia,KZN
2,2B,410,ASF,2966,MRV,2962,0,2966,Astrakhan Airport,Astrakhan,Russia,ASF,2962,Mineralnyye Vody Airport,Mineralnye Vody,Russia,MRV
3,2B,410,CEK,2968,KZN,2990,0,2968,Chelyabinsk Balandino Airport,Chelyabinsk,Russia,CEK,2990,Kazan International Airport,Kazan,Russia,KZN
4,2B,410,CEK,2968,OVB,4078,0,2968,Chelyabinsk Balandino Airport,Chelyabinsk,Russia,CEK,4078,Tolmachevo Airport,Novosibirsk,Russia,OVB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67658,ZL,4178,WYA,6334,ADL,3341,0,6334,Whyalla Airport,Whyalla,Australia,WYA,3341,Adelaide International Airport,Adelaide,Australia,ADL
67659,ZM,19016,DME,4029,FRU,2912,0,4029,Domodedovo International Airport,Moscow,Russia,DME,2912,Manas International Airport,Bishkek,Kyrgyzstan,FRU
67660,ZM,19016,FRU,2912,DME,4029,0,2912,Manas International Airport,Bishkek,Kyrgyzstan,FRU,4029,Domodedovo International Airport,Moscow,Russia,DME
67661,ZM,19016,FRU,2912,OSS,2913,0,2912,Manas International Airport,Bishkek,Kyrgyzstan,FRU,2913,Osh Airport,Osh,Kyrgyzstan,OSS
67662,ZM,19016,OSS,2913,FRU,2912,0,2913,Osh Airport,Osh,Kyrgyzstan,OSS,2912,Manas International Airport,Bishkek,Kyrgyzstan,FRU

In [69]:
df_merged_data = pd.DataFrame(merged_data[["Airport Name_x", "City_x", "Airport Name_y", "City_y", 'Stops']])
df_merged_data.rename(columns = {"Airport Name_x":"Source Airport", "City_x":"Source City", "Airport Name_y":"Destination Airport", "City_y":"Destination City"}, inplace = True)
df_merged_data

,Source Airport,Source City,Destination Airport,Destination City,Stops
0,Sochi International Airport,Sochi,Kazan International Airport,Kazan,0
1,Astrakhan Airport,Astrakhan,Kazan International Airport,Kazan,0
2,Astrakhan Airport,Astrakhan,Mineralnyye Vody Airport,Mineralnye Vody,0
3,Chelyabinsk Balandino Airport,Chelyabinsk,Kazan International Airport,Kazan,0
4,Chelyabinsk Balandino Airport,Chelyabinsk,Tolmachevo Airport,Novosibirsk,0
...,...,...,...,...,...
67658,Whyalla Airport,Whyalla,Adelaide International Airport,Adelaide,0
67659,Domodedovo International Airport,Moscow,Manas International Airport,Bishkek,0
67660,Manas International Airport,Bishkek,Domodedovo International Airport,Moscow,0
67661,Manas International Airport,Bishkek,Osh Airport,Osh,0
67662,Osh Airport,Osh,Manas International Airport,Bishkek,0

And here is the edges we want:

In [71]:
edges = []

for index, row in df_merged_data.iterrows():
    source_city = row["Source City"]
    destination_city = row["Destination City"]

    if pd.notna(source_city) and pd.notna(destination_city):
        edges.append((source_city, destination_city))
edges[:15]

[('Sochi', 'Kazan'),
 ('Astrakhan', 'Kazan'),
 ('Astrakhan', 'Mineralnye Vody'),
 ('Chelyabinsk', 'Kazan'),
 ('Chelyabinsk', 'Novosibirsk'),
 ('Moscow', 'Kazan'),
 ('Moscow', 'Nizhnekamsk'),
 ('Moscow', 'Taganrog'),
 ('Moscow', 'Bugulma'),
 ('Belgorod', 'Kaliningrad'),
 ('Belgorod', 'Kazan'),
 ('Baku', 'Nizhnekamsk'),
 ('Kaliningrad', 'Belgorod'),
 ('Kazan', 'Sochi'),
 ('Kazan', 'Astrakhan')]

We need shortest paths for Antalya-Deer Lake, Adana-Auckland, Ankara-Kona and Sydney-Churchill so I used shortest_path function from networkx library.

In [73]:
G = nx.from_edgelist(set(edges))

routes = {
    ('Antalya', 'Deer Lake'): nx.shortest_path(G, source='Antalya', target='Deer Lake'),
    ('Adana', 'Auckland'): nx.shortest_path(G, source='Adana', target='Auckland'),
    ('Ankara', 'Kona'): nx.shortest_path(G, source='Ankara', target='Kona'),
    ('Sydney', 'Churchhill'): nx.shortest_path(G, source='Sydney', target='Churchill')
}

for route, path in routes.items():
    print(f"From {route[0]} to {route[1]} route: {path}")

From Antalya to Deer Lake route: ['Antalya', 'London', "St. John's", 'Deer Lake']
From Adana to Auckland route: ['Adana', 'Istanbul', 'Singapore', 'Auckland']
From Ankara to Kona route: ['Ankara', 'Munich', 'Vancouver', 'Kona']
From Sydney to Churchhill route: ['Sydney', 'Vancouver', 'Winnipeg', 'Churchill']

And for Page Ranks, I used pagerank funcitons.

In [74]:
pagerank_scores = nx.pagerank(G)

top_cities = sorted(pagerank_scores.items(), key=lambda item: -item[1])[:10]

for city, score in top_cities:
    print(f"{city} : {score}")

London : 0.006337402865762115
Moscow : 0.006176392146938519
Paris : 0.005569215499026182
Istanbul : 0.005328465704670041
Atlanta : 0.004694651978335464
Chicago : 0.004628672052045807
Denver : 0.004457030729019318
Dallas-Fort Worth : 0.004439269834907625
Beijing : 0.004412097366113177
Amsterdam : 0.004333366675389221